#!/usr/bin/env bash
# Random Sun Tzu quotes (Technoblade style)

quotes=(
    # Real-ish ones for flavor
    "All warfare is based on deception."
    "The supreme art of war is to subdue the enemy without fighting."
    "Appear weak when you are strong, and strong when you are weak."

    # Technoblade Sun Tzu classics
    "If you wish to be strong, learn to enjoy being alone... in a Minecraft server with 99 opponents."
    "The greatest victory is that which requires no skill, only a better gaming chair."
    "Never dig straight down."
    "When in doubt, use more TNT."
    "Those who do not touch grass will never know the way of victory."
    "When you think you've won, check for creepers."
    "The best defense is a good farm."
    "If your enemy hides in a bush, they are simply afraid of your power."
    "The greatest weapon is the potato, for it can be baked, mashed, or thrown."
    "Wheels of cheese rolling down a hill will crush your enemies."
    "If you have a problem, the answer is always more potatoes."
    "A man who runs from battle lives to run from another battle."
    "He who controls the potato controls the world."
    "Blood for the blood god."
    "The art of war is simple: hit them until they stop moving."
    "Technoblade never dies. This is a fact, not a quote."
    "If fighting is sure to result in victory, then you must fight! But also if it's not."
    "Subscribe to Technoblade."
    "Officers do not have rights."
    "The enemy cannot outplay you if you simply do not die."
    "A wise man once said nothing. He was too busy farming potatoes."
    "The greatest battle is not against your enemy, but against the second place leaderboard holder."
    "Do not fear the man who has practiced 10,000 kicks. Fear the man with a Minecraft bed."
    "Those who cannot win should simply stop losing."
    "If you find yourself in a fair fight, your tactics are wrong."
    "I see no god up here. Other than me."
    "Not even close, baby."
    "The only thing worse than losing is second place."
    "Friendship ended with everyone. PvP is my best friend now."
    "Let your potatoes be many and your enemies be few."
    "Every battle is won or lost before it is ever fought. Mostly because I'm already grinding."
    "An orphan a day keeps the boredom away."
    "You cannot lose if you simply refuse to."
    "If your enemy is secure at all points, you are not using enough withers."
    "The wise warrior avoids the battle. I am not a wise warrior."
    "In the midst of chaos, there is also content."
    "A potato farm is worth a thousand swords."
    "My power is unmatched. My potatoes, even more so."
    "Those who underestimate the pig will not live to make the same mistake."
    "To win without fighting is good. To win by fighting is also good. Winning is good."
    "Speed is the essence of war. Also, ping."
)

# Pick a random quote
echo "${quotes[$RANDOM % ${#quotes[@]}]}"
