# Compiler flags for Apple Silicon M1
COMMON_FLAGS="-O2 -pipe -mcpu=apple-m1"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

CHOST="aarch64-unknown-linux-gnu"

MAKEOPTS="-j7"
EMERGE_DEFAULT_OPTS="--jobs=2 --load-average=7"

USE="wayland vulkan pipewire dbus screencast -X -gnome -kde"

VIDEO_CARDS="asahi"
INPUT_DEVICES="libinput"

ACCEPT_KEYWORDS="~arm64"

PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

PORTAGE_ELOG_CLASSES="warn error info log qa"
PORTAGE_ELOG_SYSTEM="save"

LC_MESSAGES=C.UTF-8

ACCEPT_LICENSE="-* @FREE freedist"
