#!/usr/bin/env bash
# Random Sun Tzu quotes (real and "real")

quotes=(
    "The supreme art of war is to subdue the enemy without fighting."
    "In the midst of chaos, there is also opportunity."
    "Know yourself and you will win all battles."
    "Appear weak when you are strong, and strong when you are weak."
    "The greatest victory is that which requires no battle."
    "If you wait by the river long enough, the bodies of your enemies will float by."
    "He who is prudent and lies in wait for an enemy who is not, will be victorious."
    "Never interrupt your enemy when he is making a mistake."
    "If fighting is sure to result in victory, then you must fight."
    "The opportunity of defeating the enemy is provided by the enemy himself."
    "Victorious warriors win first and then go to war."
    "Those who do not plan, plan to fail."
    "The whole secret lies in confusing the enemy."
    "Speed is the essence of war."
    "All warfare is based on deception."
    "If your opponent is of choleric temper, irritate him."
    "The wise warrior avoids the battle."
    "He will win who knows when to fight and when not to fight."
    "When you surround an army, leave an outlet free."
    "Treat your men as you would your own beloved sons."
    "Pretend inferiority and encourage his arrogance."
    "To know your enemy, you must become your enemy."
    "Move swift as the wind and closely-formed as the wood."
    "The quality of decision is like the well-timed swoop of a falcon."
    "If your enemy is secure at all points, be prepared for him."
    "When strong, avoid them. If of high morale, depress them."
    "Build your opponent a golden bridge to retreat across."
    "One may know how to conquer without being able to do it."
    "When the enemy is relaxed, make them toil."
    "Be extremely subtle, even to the point of formlessness."
    "Let your plans be dark and impenetrable as night."
    "Water shapes its course according to the nature of the ground."
    "The skillful tactician may be likened to the shuai-jan."
    "Rapidity is the essence of war."
    "The value of time, that is of being a little ahead of your opponent."
    "Swiftness is the essence of war."
    "In battle, there are not more than two methods of attack."
    "The good fighters of old first put themselves beyond possibility of defeat."
    "If you know neither the enemy nor yourself, you will succumb in every battle."
    "Who wishes to fight must first count the cost."
    "He who advances without seeking fame retreats without avoiding disgrace."
    "There is no instance of a nation benefitting from prolonged warfare."
    "Quickness is the essence of the war."
    "What the ancients called a clever fighter is one who wins but excels in winning with ease."
    "Supreme excellence consists of breaking the enemys resistance without fighting."
    "Thus the expert in battle moves the enemy, and is not moved by him."
    "A leader leads by example, not by force."
    "The art of war teaches us not to rely on the likelihood of the enemy not coming."
    "Wheels of cheese rolling down a hill will crush your enemies."
    "Never dig straight down."
    "When in doubt, use more TNT."
    "The greatest weapon is the potato, for it can be baked, mashed, or thrown."
    "If your enemy hides in a bush, they are simply afraid of your power."
    "A blade of grass that bends in the wind will outlast the mighty oak."
    "Those who do not touch grass will never know the way of victory."
    "The best defense is a good farm."
    "When you think you've won, check for creepers."
)

# Pick a random quote
echo "${quotes[$RANDOM % ${#quotes[@]}]}"
