# /* wallust template - colors-kitty */

foreground         #E3DFDB
background         #141414
cursor             #807D7A

active_tab_foreground     #141414
active_tab_background     #E3DFDB
inactive_tab_foreground   #E3DFDB
inactive_tab_background   #141414

active_border_color   #E3DFDB
inactive_border_color #141414
bell_border_color     #101010

color0      #3B3B3B
color1		#101010
color2		#161412
color3		#463327
color4		#393B3B
color5		#704E3A
color6		#827A73
color7		#CEC9C4
color8		#908C89
color9		#151515
color10		#1D1A18
color11		#5D4434
color12		#4C4F4E
color13		#95684D
color14		#AEA399
color15		#CEC9C4
