# created by eselect-repo

[asahi]
location = /var/db/repos/asahi
sync-type = git
sync-uri = https://github.com/chadmed/asahi-overlay.git

[hyproverlay]
location = /var/db/repos/hyproverlay
sync-type = git
sync-uri = https://codeberg.org/hyproverlay/hyproverlay.git
