foreground #a6accd
background #1b1e28
cursor #a6accd
cursor_text_color #1b1e28
selection_foreground #1b1e28
selection_background #a6accd

color0 #1b1e28
color1 #d0679d
color2 #5de4c7
color3 #fffac2
color4 #add7ff
color5 #f087bd
color6 #89ddff
color7 #a6accd
color8 #303446
color9 #d0679d
color10 #5de4c7
color11 #fffac2
color12 #add7ff
color13 #f087bd
color14 #89ddff
color15 #e4f0fb
